Update deploytest.yml

diff --git a/.github/workflows/deploytest.yml b/.github/workflows/deploytest.yml
--- a/.github/workflows/deploytest.yml
+++ b/.github/workflows/deploytest.yml
@@ -20,7 +20,12 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-
+      - name: Very file present
+        run: |
+          if [ ! -f "my-app.txt" ]; then
+            echo "File not found: my-app.txt"
+            exit 1
+          fi
       - name: Deploy application
         run: |
           aws s3 cp my-app.txt s3://demokarthik06/
